version: "3.9"
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - my_db:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - 8080:8080
volumes:
  my_db: